# Generated by Django 5.2.1 on 2025-07-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
    ]
